name: pl-forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=2.3.3
  - astropy=3.2.3
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.13.2
  - colorama=0.4.1
  - confuse=1.0.0
  - cryptography=2.8
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - graphviz=2.38
  - htmlmin=0.1.12
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.1.1
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.3
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvmlite=0.30.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - missingno=0.4.2
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - notebook=6.0.1
  - numba=0.46.0
  - numpy-base=1.17.3
  - openssl=1.1.1d
  - packaging=19.2
  - pandas-profiling=2.3.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - patsy=0.5.1
  - phik=0.9.8
  - pickleshare=0.7.5
  - pip=19.3.1
  - pluggy=0.12.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - psutil=5.6.5
  - py=1.8.0
  - pycparser=2.19
  - pygments=2.4.2
  - pylint=2.4.3
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - pytest=5.2.2
  - pytest-arraydiff=0.3
  - pytest-astropy=0.6.0
  - pytest-astropy-header=0.1.1
  - pytest-doctestplus=0.4.0
  - pytest-openfiles=0.4.0
  - pytest-pylint=0.14.1
  - pytest-remotedata=0.3.1
  - pytest-runner=5.2
  - python=3.6.9
  - python-graphviz=0.13
  - pytz=2019.3
  - pywin32=223
  - pywinpty=0.5.5
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - requests=2.22.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.6.0
  - sip=4.19.8
  - sqlite=3.30.1
  - statsmodels=0.10.1
  - tbb=2019.9
  - terminado=0.8.2
  - testpath=0.4.2
  - traitlets=4.3.3
  - typed-ast=1.4.0
  - urllib3=1.25.6
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - arrow==0.15.4
    - astor==0.8.0
    - binaryornot==0.4.4
    - blinker==1.4
    - boto3==1.10.13
    - botocore==1.13.13
    - chardet==3.0.4
    - click==7.0
    - cookiecutter==1.6.0
    - docutils==0.15.2
    - enum-compat==0.0.3
    - future==0.18.2
    - idna==2.8
    - isoweek==1.3.3
    - jinja2-time==0.2.0
    - jmespath==0.9.4
    - joblib==0.14.0
    - numpy==1.17.3
    - pandas==0.25.3
    - pandas-summary==0.0.7
    - poyo==0.5.0
    - protobuf==3.10.0
    - python-dateutil==2.8.1
    - s3transfer==0.2.1
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - six==1.13.0
    - sklearn-pandas==1.8.0
    - tornado==5.1.1
    - tzlocal==2.0.0
    - validators==0.14.0
    - whichcraft==0.6.1



